'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Wand2, 
  ListTodo, 
  FileText, 
  Share2, 
  Loader2, 
  TrendingUp, 
  BrainCircuit,
  Download,
  CheckCircle2,
  Twitter,
  Linkedin,
  Instagram,
  RefreshCw,
  Plus
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { 
  generateSocialMediaPosts, 
  generateOrganizerTasks, 
  generateFullEventReport,
  getPredictiveAttendance 
} from '@/app/actions/event-insights';
import { cn } from '@/core/utils/utils';
import { jsPDF } from 'jspdf';

interface AIInsightsClientProps {
  eventId: string;
}

export function AIInsightsClient({ eventId }: AIInsightsClientProps) {
  const { toast } = useToast();
  const [loadingAction, setLoadingAction] = useState<string | null>(null);
  
  // Data State
  const [socialPosts, setSocialPosts] = useState<string[]>([]);
  const [tasks, setTasks] = useState<string[]>([]);
  const [report, setReport] = useState<any>(null);
  const [prediction, setPrediction] = useState<any>(null);

  const handleAction = async (actionName: string, fn: () => Promise<any>) => {
    setLoadingAction(actionName);
    try {
      const result = await fn();
      if (result.success === false) throw new Error(result.error);
      
      toast({ title: "AI Generation Complete", description: `Successfully generated ${actionName}.` });
      return result;
    } catch (error: any) {
      toast({ title: "AI Error", description: error.message, variant: "destructive" });
    } finally {
      setLoadingAction(null);
    }
  };

  const loadSocialPosts = () => handleAction('Social Posts', async () => {
    const data = await generateSocialMediaPosts(eventId);
    setSocialPosts(data);
    return data;
  });

  const loadTasks = () => handleAction('Task List', async () => {
    const data = await generateOrganizerTasks(eventId);
    if (data.success) setTasks(data.tasks);
    return data;
  });

  const loadReport = () => handleAction('Full Report', async () => {
    const data = await generateFullEventReport(eventId);
    if (data.success) setReport(data.report);
    return data;
  });

  const exportReportPDF = () => {
    if (!report) return;
    
    const doc = new jsPDF();
    const margin = 20;
    let y = 20;

    // Header
    doc.setFontSize(22);
    doc.setTextColor(6, 182, 212); // Cyan-500
    doc.text("EVENTRA AI INSIGHTS", margin, y);
    y += 10;
    
    doc.setFontSize(16);
    doc.setTextColor(31, 41, 55); // Gray-800
    doc.text(report.title, margin, y);
    y += 15;

    // KPIs
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE KPIs", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Total Revenue: $${report.kpis.totalRevenue}`, margin, y);
    doc.text(`Total Attendees: ${report.kpis.totalAttendees}`, margin + 60, y);
    doc.text(`Capacity Usage: ${report.kpis.capacityUtilization}%`, margin + 120, y);
    y += 10;

    // Executive Summary
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("EXECUTIVE SUMMARY", margin, y);
    y += 7;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    const lines = doc.splitTextToSize(report.executiveSummary, 170);
    doc.text(lines, margin, y);
    y += (lines.length * 5) + 10;

    // Sentiment
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("ATTENDEE SENTIMENT", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Overall Tone: ${report.sentiment.overallSentiment.toUpperCase()}`, margin, y);
    y += 5;
    doc.text(`Key Themes: ${report.sentiment.keyThemes.join(", ")}`, margin, y);
    y += 15;

    // Tier Breakdown
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("TICKET SALES BREAKDOWN", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    report.tierBreakdown.forEach((tier: any) => {
      doc.text(`${tier.name}: ${tier.sold} sold ($${tier.revenue})`, margin, y);
      y += 5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(`Generated by Eventra Intelligence on ${new Date().toLocaleString()}`, margin, 280);

    doc.save(`AAR-${eventId}.pdf`);
    toast({ title: "PDF Generated", description: "Your report is ready for download." });
  };

  const loadPrediction = () => handleAction('Prediction', async () => {
    const data = await getPredictiveAttendance(eventId);
    setPrediction(data);
    return data;
  });

  return (
    <div className="space-y-8">
      {/* Prediction Banner */}
      <Card className="bg-gradient-to-r from-cyan-900/40 to-purple-900/40 border-cyan-500/30 text-white overflow-hidden relative">
        <div className="absolute top-0 right-0 p-4 opacity-10">
           <BrainCircuit size={120} />
        </div>
        <CardContent className="p-8 relative z-10">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-8">
            <div className="space-y-2">
              <Badge className="bg-cyan-500 hover:bg-cyan-400">AI Predictive Engine</Badge>
              <h2 className="text-3xl font-black">Attendance Forecasting</h2>
              <p className="text-cyan-100/70 max-w-md">Our neural network analyzes your current registration trends and historical data to predict final turnout.</p>
            </div>

            <div className="flex items-center gap-6 bg-black/20 p-6 rounded-2xl border border-white/5 backdrop-blur-md">
              {prediction ? (
                <div className="text-center">
                   <p className="text-[10px] uppercase font-bold text-cyan-400 tracking-widest mb-1">Predicted Total</p>
                   <p className="text-5xl font-black">{prediction.predictedTotal}</p>
                   <p className="text-xs text-emerald-400 mt-1 font-bold">Confidence: {prediction.confidenceScore}%</p>
                </div>
              ) : (
                <Button 
                  className="bg-white text-black hover:bg-cyan-50" 
                  onClick={loadPrediction}
                  disabled={loadingAction === 'Prediction'}
                >
                  {loadingAction === 'Prediction' ? <Loader2 className="animate-spin mr-2" /> : <TrendingUp className="mr-2" />}
                  Generate Forecast
                </Button>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Task List Generation */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
             <h3 className="text-lg font-bold flex items-center gap-2">
                <ListTodo className="text-purple-400" /> Organizer Assistant
             </h3>
             <Button variant="ghost" size="sm" onClick={loadTasks} disabled={loadingAction === 'Task List'}>
                {loadingAction === 'Task List' ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
             </Button>
          </div>
          
          <Card className="bg-white/5 border-white/10 text-white min-h-[400px] flex flex-col">
            <CardHeader>
              <CardTitle className="text-sm">Dynamic Task List</CardTitle>
              <CardDescription>AI-generated checklist for your event lifecycle.</CardDescription>
            </CardHeader>
            <CardContent className="flex-1">
              {tasks.length > 0 ? (
                <div className="space-y-3">
                  {tasks.map((task, i) => (
                    <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-white/5 border border-white/5 group hover:border-purple-500/30 transition-all">
                       <div className="w-5 h-5 rounded border border-white/20 mt-0.5 flex-none group-hover:border-purple-500 transition-colors" />
                       <span className="text-sm text-gray-300">{task}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="h-full flex flex-col items-center justify-center text-center p-8 opacity-40">
                   <ListTodo size={48} className="mb-4" />
                   <p className="text-sm">No tasks generated yet. Let the AI build your plan.</p>
                   <Button variant="link" className="text-purple-400 mt-4" onClick={loadTasks}>Generate Tasks</Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Marketing Copilot */}
        <div className="space-y-6">
          <div className="flex items-center justify-between">
             <h3 className="text-lg font-bold flex items-center gap-2">
                <Share2 className="text-emerald-400" /> Marketing Copilot
             </h3>
             <Button variant="ghost" size="sm" onClick={loadSocialPosts} disabled={loadingAction === 'Social Posts'}>
                {loadingAction === 'Social Posts' ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}
             </Button>
          </div>

          <Card className="bg-white/5 border-white/10 text-white min-h-[400px] flex flex-col">
            <CardHeader>
               <CardTitle className="text-sm">Viral Content Generator</CardTitle>
               <CardDescription>Tailored posts for LinkedIn, Twitter, and Instagram.</CardDescription>
            </CardHeader>
            <CardContent className="flex-1 space-y-6">
               {socialPosts.length > 0 ? (
                 socialPosts.map((post, i) => (
                   <div key={i} className="p-4 rounded-xl bg-black/20 border border-white/5 relative group">
                      <div className="absolute top-4 right-4 opacity-20 group-hover:opacity-100 transition-opacity">
                         {i === 0 && <Twitter size={14} className="text-sky-400" />}
                         {i === 1 && <Linkedin size={14} className="text-blue-400" />}
                         {i === 2 && <Instagram size={14} className="text-pink-400" />}
                      </div>
                      <p className="text-xs text-gray-400 whitespace-pre-wrap leading-relaxed">{post}</p>
                      <Button 
                        variant="ghost" 
                        size="sm" 
                        className="h-7 text-[10px] uppercase font-bold mt-4 hover:bg-white/5 w-full border border-white/5"
                        onClick={() => {
                          navigator.clipboard.writeText(post);
                          toast({ title: "Copied", description: "Post content copied to clipboard." });
                        }}
                      >
                        Copy Text
                      </Button>
                   </div>
                 ))
               ) : (
                <div className="h-full flex flex-col items-center justify-center text-center p-8 opacity-40">
                   <Share2 size={48} className="mb-4" />
                   <p className="text-sm">Ready to spread the word? Generate posts instantly.</p>
                   <Button variant="link" className="text-emerald-400 mt-4" onClick={loadSocialPosts}>Generate Posts</Button>
                </div>
               )}
            </CardContent>
          </Card>
        </div>

        {/* AI Reports */}
        <div className="space-y-6">
           <h3 className="text-lg font-bold flex items-center gap-2">
              <FileText className="text-cyan-400" /> Professional Reports
           </h3>
           
           <Card className="bg-white/5 border-white/10 text-white min-h-[400px] flex flex-col border-2 border-dashed">
             <CardHeader>
               <CardTitle className="text-sm">After Action Report (AAR)</CardTitle>
               <CardDescription>AI-synthesized analysis of financial, attendee, and feedback data.</CardDescription>
             </CardHeader>
             <CardContent className="flex-1 flex flex-col">
                {report ? (
                  <div className="space-y-6">
                     <div className="p-4 rounded-xl bg-cyan-500/10 border border-cyan-500/20">
                        <h4 className="text-xs font-black uppercase text-cyan-400 mb-2">Executive Summary</h4>
                        <p className="text-xs text-gray-300 leading-relaxed italic line-clamp-6">"{report.executiveSummary}"</p>
                     </div>
                     
                     <div className="grid grid-cols-2 gap-3">
                        <div className="p-3 bg-white/5 rounded-lg border border-white/5 text-center">
                           <p className="text-[10px] text-gray-500 uppercase">Revenue</p>
                           <p className="text-lg font-bold">${report.kpis.totalRevenue}</p>
                        </div>
                        <div className="p-3 bg-white/5 rounded-lg border border-white/5 text-center">
                           <p className="text-[10px] text-gray-500 uppercase">NPS Score</p>
                           <p className="text-lg font-bold">+{report.sentiment.overallSentiment === 'positive' ? '68' : '24'}</p>
                        </div>
                     </div>

                     <Button 
                       className="w-full bg-cyan-600 hover:bg-cyan-500 text-white mt-auto"
                       onClick={exportReportPDF}
                     >
                        <Download className="mr-2 h-4 w-4" /> Export as PDF
                     </Button>
                  </div>
                ) : (
                  <div className="flex-1 flex flex-col items-center justify-center text-center p-8 opacity-40">
                    <FileText size={48} className="mb-4" />
                    <p className="text-sm">Compile all event data into a high-level PDF report.</p>
                    <Button 
                      variant="outline" 
                      className="border-cyan-500/30 text-cyan-400 mt-6 hover:bg-cyan-500/10" 
                      onClick={loadReport}
                      disabled={loadingAction === 'Full Report'}
                    >
                      {loadingAction === 'Full Report' ? <Loader2 className="animate-spin mr-2" /> : <Wand2 className="mr-2" />}
                      Generate Report
                    </Button>
                  </div>
                )}
             </CardContent>
           </Card>
        </div>
      </div>
    </div>
  );
}
