export const api: any = {
  users: {
    viewer: "users:viewer",
    getById: "users:getById",
    update: "users:update",
    awardPoints: "users:awardPoints",
    checkIn: "users:checkIn",
    list: "users:list",
    getLeaderboard: "users:getLeaderboard",
    search: "users:search",
    searchForDM: "users:searchForDM",
    getByEmail: "users:getByEmail",
    follow: "users:follow",
    unfollow: "users:unfollow",
    getFollowStats: "users:getFollowStats",
    getEngagementScore: "users:getEngagementScore",
    generateReferralCode: "users:generateReferralCode",
    redeemReferral: "users:redeemReferral",
    getRecommended: "users:getRecommended",
    listPublicUsers: "users:listPublicUsers",
  },
  events: {
    get: "events:get",
    list: "events:list",
    getById: "events:getById",
    getByOrganizer: "events:getByOrganizer",
    getManagedEvents: "events:getManagedEvents",
    getBySpeaker: "events:getBySpeaker",
    listByOrganizer: "events:listByOrganizer",
    getByStatus: "events:getByStatus",
    listByStatus: "events:listByStatus",
    getPublished: "events:getPublished",
    create: "events:create",
    update: "events:update",
    cancelEvent: "events:cancelEvent",
    completeEvent: "events:completeEvent",
    publishEvent: "events:publishEvent",
    deleteEvent: "events:deleteEvent",
    getAttendees: "events:getAttendees",
    cloneEvent: "events:cloneEvent",
    getAnalytics: "events:getAnalytics",
    addReaction: "events:addReaction",
    getReactions: "events:getReactions",
  },
  tickets: {
    getByEventId: "tickets:getByEventId",
    getByUserId: "tickets:getByUserId",
    getMyTickets: "tickets:getMyTickets",
    createTicket: "tickets:createTicket",
    updateTicketStatus: "tickets:updateTicketStatus",
    getTicketByNumber: "tickets:getTicketByNumber",
    checkInTicket: "tickets:checkInTicket",
    cancelTicket: "tickets:cancelTicket",
  },
  chat: {
    getRooms: "chat:getRooms",
    listMessages: "chat:listMessages",
    sendMessage: "chat:sendMessage",
    markMessagesRead: "chat:markMessagesRead",
    createRoom: "chat:createRoom",
    createEventChatRoom: "chat:createEventChatRoom",
  },
  notifications: {
    get: "notifications:get",
    list: "notifications:list",
    getUnreadCount: "notifications:getUnreadCount",
    markRead: "notifications:markRead",
    deleteNotification: "notifications:deleteNotification",
    markAllRead: "notifications:markAllRead",
    create: "notifications:create",
    clearAll: "notifications:clearAll",
    subscribePush: "notifications:subscribePush",
    unsubscribePush: "notifications:unsubscribePush",
  },
  files: {
    generateUploadUrl: "files:generateUploadUrl",
    saveFile: "files:saveFile",
    getMetadata: "files:getMetadata",
  },
  admin: {
    getUsers: "admin:getUsers",
    updateUserRole: "admin:updateUserRole",
    updateUserStatus: "admin:updateUserStatus",
    getEventsForModeration: "admin:getEventsForModeration",
    moderateEvent: "admin:moderateEvent",
    getSettings: "admin:getSettings",
    updateSetting: "admin:updateSetting",
    getAuditLog: "admin:getAuditLog",
    getDashboardStats: "admin:getDashboardStats",
    getDetailedAnalytics: "admin:getDetailedAnalytics",
  },
  communities: {
    list: "communities:list",
    getById: "communities:getById",
    create: "communities:create",
    update: "communities:update",
    deleteCommunity: "communities:deleteCommunity",
    join: "communities:join",
    requestJoin: "communities:requestJoin",
    getJoinRequests: "communities:getJoinRequests",
    respondToJoinRequest: "communities:respondToJoinRequest",
    leave: "communities:leave",
    getMemberStatus: "communities:getMemberStatus",
    getMembers: "communities:getMembers",
    updateMemberRole: "communities:updateMemberRole",
    removeMember: "communities:removeMember",
  },
  posts: {
    list: "posts:list",
    listByCommunity: "posts:listByCommunity",
    create: "posts:create",
    update: "posts:update",
    like: "posts:like",
    hasLiked: "posts:hasLiked",
    deletePost: "posts:deletePost",
    getComments: "posts:getComments",
    addComment: "posts:addComment",
  },
  gamification: {
    getBadgeDefinitions: "gamification:getBadgeDefinitions",
    getUserBadges: "gamification:getUserBadges",
    getPointsHistory: "gamification:getPointsHistory",
    addPoints: "gamification:addPoints",
    awardBadge: "gamification:awardBadge",
    getChallenges: "gamification:getChallenges",
    getUserChallenges: "gamification:getUserChallenges",
    joinChallenge: "gamification:joinChallenge",
    updateChallengeProgress: "gamification:updateChallengeProgress",
    triggerChallengeProgress: "gamification:triggerChallengeProgress",
    getProfile: "gamification:getProfile",
  },
  registrations: {
    register: "registrations:register",
    cancel: "registrations:cancel",
    getRegistration: "registrations:getRegistration",
    getByEvents: "registrations:getByEvents",
    getByUser: "registrations:getByUser",
    getUpcoming: "registrations:getUpcoming",
  },
  reviews: {
    getByEvent: "reviews:getByEvent",
  },
  certificates: {
    issue: "certificates:issue",
    bulkIssue: "certificates:bulkIssue",
    getByUser: "certificates:getByUser",
    getByEvent: "certificates:getByEvent",
    getByEventAndUser: "certificates:getByEventAndUser",
    verify: "certificates:verify",
  },
  analytics: {
    createShareLink: "analytics:createShareLink",
    getSharedReport: "analytics:getSharedReport",
    incrementReportView: "analytics:incrementReportView",
    getOrganizerRevenue: "analytics:getOrganizerRevenue",
  },
  search: {
    globalSearch: "search:globalSearch",
  },
  automations: {
    get: "automations:get",
    create: "automations:create",
    toggle: "automations:toggle",
    deleteAutomation: "automations:deleteAutomation",
  },
  announcements: {
    create: "announcements:create",
    getActiveByEvent: "announcements:getActiveByEvent",
    deactivate: "announcements:deactivate",
  },
  discounts: {
    validate: "discounts:validate",
    create: "discounts:create",
    incrementUsage: "discounts:incrementUsage",
    listByEvent: "discounts:listByEvent",
    deactivate: "discounts:deactivate",
  },
};

export const internal: any = {
  webhooks: {
    trigger: "webhooks:trigger",
  },
  events: {
    autoCompletePastEvents: "events:autoCompletePastEvents",
  },
  tickets: {
    processRefund: "tickets:processRefund",
  },
  registrations: {
    confirmPayment: "registrations:confirmPayment",
  },
};
