'use server';

export async function generateSocialMediaPosts(_eventId: string) {
  return ['Mock post 1', 'Mock post 2'];
}

export async function getPredictiveAttendance(_eventId: string) {
  return { predicted: 100, confidence: 0.8 };
}

export async function generateEventSummary(_eventId: string) {
  return 'This is a mock event summary generated by AI.';
}
