'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import {
  Loader2,
  Plus,
  Trash2,
  GripVertical,
  Clock,
  Sparkles,
  CheckCircle2,
  Circle,
  MoreHorizontal,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { getEventTasks, saveEventTasks, updateTaskColumn } from '@/app/actions/kanban-tasks';
import { generateEventTasks } from '@/app/actions/ai-tasks';

const COLUMNS = [
  { id: 'planning', label: 'Planning', color: 'bg-blue-500/10 border-blue-500/20', headerColor: 'bg-blue-500/10' },
  { id: 'developing', label: 'In Progress', color: 'bg-amber-500/10 border-amber-500/20', headerColor: 'bg-amber-500/10' },
  { id: 'reviewing', label: 'Review', color: 'bg-purple-500/10 border-purple-500/20', headerColor: 'bg-purple-500/10' },
  { id: 'finished', label: 'Completed', color: 'bg-green-500/10 border-green-500/20', headerColor: 'bg-green-500/10' },
];

const PRIORITIES = [
  { value: 'high', label: 'High', color: 'bg-red-500/10 text-red-500' },
  { value: 'medium', label: 'Medium', color: 'bg-amber-500/10 text-amber-500' },
  { value: 'low', label: 'Low', color: 'bg-green-500/10 text-green-500' },
];

interface KanbanBoardProps {
  eventId: string;
}

export function KanbanBoard({ eventId }: KanbanBoardProps) {
  const { toast } = useToast();
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [editingTask, setEditingTask] = useState<any>(null);
  const [draggedTask, setDraggedTask] = useState<string | null>(null);

  const [form, setForm] = useState({
    content: '',
    column: 'planning',
    priority: 'medium',
    estimatedDuration: '',
  });

  useEffect(() => {
    loadTasks();
  }, [eventId]); // eslint-disable-line react-hooks/exhaustive-deps

  const loadTasks = async () => {
    setLoading(true);
    try {
      const data = await getEventTasks(eventId);
      setTasks(data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateTasks = async () => {
    setGenerating(true);
    try {
      const result = await generateEventTasks(eventId);
      if (result.success && result.tasks) {
        await saveEventTasks(eventId, result.tasks);
        setTasks(result.tasks);
        toast({ title: 'Tasks generated by AI' });
      } else {
        toast({ title: result.error || 'Generation failed', variant: 'destructive' });
      }
    } catch (e) {
      toast({ title: 'AI generation failed', variant: 'destructive' });
    } finally {
      setGenerating(false);
    }
  };

  const handleAddTask = () => {
    if (!form.content) {
      toast({ title: 'Enter task content', variant: 'destructive' });
      return;
    }
    const newTask = {
      id: `task-${Date.now()}`,
      content: form.content,
      column: form.column,
      priority: form.priority,
      estimatedDuration: form.estimatedDuration || 'TBD',
      completed: false,
      subtasks: [],
    };
    const updated = [...tasks, newTask];
    setTasks(updated);
    saveEventTasks(eventId, updated);
    setShowAddDialog(false);
    setForm({ content: '', column: 'planning', priority: 'medium', estimatedDuration: '' });
    toast({ title: 'Task added' });
  };

  const handleDeleteTask = (taskId: string) => {
    const updated = tasks.filter(t => t.taskId !== taskId && t.id !== taskId);
    setTasks(updated);
    saveEventTasks(eventId, updated);
  };

  const handleMoveTask = (taskId: string, newColumn: string) => {
    const updated = tasks.map(t => {
      if ((t.taskId || t.id) === taskId) {
        return { ...t, column: newColumn };
      }
      return t;
    });
    setTasks(updated);
    saveEventTasks(eventId, updated);
  };

  const handleToggleSubtask = (taskId: string, subtaskIndex: number) => {
    const updated = tasks.map(t => {
      if ((t.taskId || t.id) === taskId) {
        const subtasks = [...(t.subtasks || [])];
        if (subtasks[subtaskIndex]) {
          subtasks[subtaskIndex] = { ...subtasks[subtaskIndex], completed: !subtasks[subtaskIndex].completed };
        }
        return { ...t, subtasks };
      }
      return t;
    });
    setTasks(updated);
    saveEventTasks(eventId, updated);
  };

  const getTasksByColumn = (columnId: string) =>
    tasks.filter(t => t.column === columnId);

  const getPriorityConfig = (priority: string) => PRIORITIES.find(p => p.value === priority) || PRIORITIES[1];

  if (loading) {
    return (
      <div className="flex justify-center py-12"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold">Task Board</h2>
          <p className="text-muted-foreground text-sm">Plan and track event preparation tasks</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleGenerateTasks} disabled={generating}>
            {generating ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Sparkles className="h-4 w-4 mr-2" />}
            AI Generate
          </Button>
          <Button onClick={() => setShowAddDialog(true)}>
            <Plus className="h-4 w-4 mr-2" /> Add Task
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {COLUMNS.map((col) => {
          const colTasks = getTasksByColumn(col.id);
          return (
            <div
              key={col.id}
              className={`rounded-xl border ${col.color} p-3 min-h-[200px]`}
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => {
                e.preventDefault();
                if (draggedTask) {
                  handleMoveTask(draggedTask, col.id);
                  setDraggedTask(null);
                }
              }}
            >
              <div className={`flex items-center justify-between mb-3 px-1 ${col.headerColor} rounded-lg p-2`}>
                <h3 className="font-semibold text-sm">{col.label}</h3>
                <Badge variant="secondary" className="text-[10px]">{colTasks.length}</Badge>
              </div>
              <div className="space-y-2">
                {colTasks.map((task) => {
                  const taskId = task.taskId || task.id;
                  const priorityConfig = getPriorityConfig(task.priority);
                  const completedSubtasks = (task.subtasks || []).filter((s: any) => s.completed).length;
                  const totalSubtasks = (task.subtasks || []).length;
                  return (
                    <Card
                      key={taskId}
                      className="cursor-grab active:cursor-grabbing hover:shadow-md transition-shadow bg-white dark:bg-zinc-900"
                      draggable
                      onDragStart={() => setDraggedTask(taskId)}
                    >
                      <CardContent className="p-3">
                        <div className="flex items-start justify-between gap-2">
                          <p className="text-sm font-medium flex-1">{task.content}</p>
                          <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0" onClick={() => handleDeleteTask(taskId)}>
                            <Trash2 className="h-3 w-3" />
                          </Button>
                        </div>
                        <div className="flex items-center gap-2 mt-2 flex-wrap">
                          <Badge className={priorityConfig.color} variant="secondary">{priorityConfig.label}</Badge>
                          {task.estimatedDuration && (
                            <span className="text-[10px] text-muted-foreground flex items-center gap-1">
                              <Clock className="h-3 w-3" /> {task.estimatedDuration}
                            </span>
                          )}
                        </div>
                        {totalSubtasks > 0 && (
                          <div className="mt-2 space-y-1">
                            {(task.subtasks || []).map((sub: any, idx: number) => (
                              <div
                                key={sub.id || idx}
                                className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer hover:text-foreground"
                                onClick={() => handleToggleSubtask(taskId, idx)}
                              >
                                {sub.completed ? <CheckCircle2 className="h-3 w-3 text-green-500" /> : <Circle className="h-3 w-3" />}
                                <span className={sub.completed ? 'line-through' : ''}>{sub.content}</span>
                              </div>
                            ))}
                            <p className="text-[10px] text-muted-foreground">{completedSubtasks}/{totalSubtasks} done</p>
                          </div>
                        )}
                      </CardContent>
                    </Card>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Add Task</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <Label>Task</Label>
              <Textarea placeholder="What needs to be done?" rows={2} value={form.content} onChange={(e) => setForm({ ...form, content: e.target.value })} />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Column</Label>
                <Select value={form.column} onValueChange={(v) => setForm({ ...form, column: v })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {COLUMNS.map(c => <SelectItem key={c.id} value={c.id}>{c.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label>Priority</Label>
                <Select value={form.priority} onValueChange={(v) => setForm({ ...form, priority: v })}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {PRIORITIES.map(p => <SelectItem key={p.value} value={p.value}>{p.label}</SelectItem>)}
                  </SelectContent>
                </Select>
              </div>
            </div>
            <div>
              <Label>Estimated Duration</Label>
              <Input placeholder="e.g. 2-3 days" value={form.estimatedDuration} onChange={(e) => setForm({ ...form, estimatedDuration: e.target.value })} />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAddDialog(false)}>Cancel</Button>
            <Button onClick={handleAddTask}>Add Task</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
